[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.docker",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = ["CPython==3.10.*"]

[docker]
env_vars = ["DOCKER_DEFAULT_PLATFORM=linux/amd64"]

[environments-preview.names]
linux_x86 = "//:linux_x86"
docker = "//:docker"
